apiVersion: v1
kind: Service
metadata:
  name: data-ingress-backend
spec:
  ports:
    - port: 443
      targetPort: 9028
  selector:
    app: data-ingress-backend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-ingress-backend
spec:
  selector:
    matchLabels:
      app: data-ingress-backend
  replicas: 3
  template:
    metadata:
      labels:
        app: data-ingress-backend
    spec:
      containers:
        - name: data-ingress-backend
          image: ghcr.io/railtrack-sense/data_ingress_backend:latest
          ports:
            - containerPort: 9028

          volumeMounts:
            - name: tls-secret
              mountPath: /etc/ssl/certs/rts_certs
              readOnly: true

      imagePullSecrets:
        - name: github-registry-secret
      volumes:
        - name: tls-secret
          secret:
            secretName: rts-tls-secret